name: Hugging Face Space Login Workflow

on:
  push:
    branches: [main]

jobs:
  login-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Playwright
        run: npm install playwright

      - name: Run login script
        env:
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_PASSWORD: ${{ secrets.HF_PASSWORD }}
        run: |
          cat << 'EOF' > login.js
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch();
            const context = await browser.newContext();
            const page = await context.newPage();
            await page.goto('https://huggingface.co/login');
            await page.fill('input[name="username"]', process.env.HF_USERNAME);
            await page.fill('input[name="password"]', process.env.HF_PASSWORD);
            await page.click('button[type="submit"]');
            // Wait for a user-specific element to confirm login succeeded
            await page.waitForSelector('text=My profile');
            console.log('Login successful');
            await browser.close();
          })();
          EOF
          node login.js
